### ISSUE TITLE
可以出一个编译教程吗

### ISSUE THREAD

**Issue by zhengbomo** [yellowei/CYFFmpeg#1]
可以编译成静态库吗，通常有很多功能是没用到的，动态库有点浪费

**Comment by yellowei** [comment]
静态库之前有做过，后来发现使用起来不方便，现在可以通过pods直接安装CYFFmpeg

**Comment by zhengbomo** [comment]
pod引入是动态库，用起来体积比较大，一般来说有很多功能用不到

**Comment by yellowei** [comment]
由于静态库在链接时需要链接到可执行文件中，所以会导致包体积变大。动态库因为不会添加到可执行文件中，所以相比静态库包体积会小一些。

**Comment by zhengbomo** [comment]
静态库只是可执行文件变大，包体积实际会更小，静态库链接会optimize，丢弃不用的符号和方法，而动态库则是完全引入

**Comment by yellowei** [comment]
对于这个问题，我不是专家，所以特地查了相关资料希望能帮助到你。有一点说的没错，动态库和静态库的区别在于链接时候的方式不同，使用静态库的程序，编译时被链接到目标代码中参与编译，链接时将库完整地拷贝至可执行文件中，被多次使用的静态库就有多份冗余拷贝；使用动态库的程序，运行时由系统动态加载动态库到内存，供程序调用，系统只加载一次，多个程序共用，节省内存。对于ipa打包，简书有一篇讲得比较详细的文章：http://events.jianshu.io/p/2dd7fe0c4333

**Comment by zhengbomo** [comment]
好的，感谢，使用静态库主要的考虑是
ffmpeg这个库包含的东西太多了，很多时候用不到这么多东西，静态库链接可以丢弃不用的符号，最终产物会小很多
由于iOS沙箱机制，App的动态库只有自己用，不存在共用

**Comment by yellowei** [comment]
谢谢，你说的没错，静态库打包IPA应该是会小一些的，这让我回忆起当时为何要做成动态库了，刚刚看到你的回复我想起来了，当时从静态库转为开发动态库，是因为当时的项目中有多个第三方库使用了ffmpeg，导致“”相同符号”的问题无法链接，后来我只好将自己做的播放器改为动态库之后，才解决了这一问题，算是一种变相解决吧。
