### ISSUE TITLE
smbclient是怎么编译的

### ISSUE THREAD

**Issue by FantasyKingdom** [yellowei/CYFFmpeg#1]
我自己编译smbclient时发现要依赖一大堆的库，最后还是没有编译成功

**Comment by yellowei** [comment]
我用的samba是这个版本的： [samba](https://github.com/yellowei/Samba-iOS)

这里有个细节，就是mac系统一定要是能安装xcode8的，好像是10.12还是多少来着，这个目前而言只有老款mac才能支持了

除了Xcode 8, 别的版本不一定能成功

**Comment by yellowei** [comment]
> 我自己编译smbclient时发现要依赖一大堆的库，最后还是没有编译成功

你是什么环境下编译的？

**Comment by FantasyKingdom** [comment]
> 我用的samba是这个版本的： [samba](https://github.com/yellowei/Samba-iOS)
> 
> 这里有个细节，就是mac系统一定要是能安装xcode8的，好像是10.12还是多少来着，这个目前而言只有老款mac才能支持了
> 
> 除了Xcode 8, 别的版本不一定能成功

好的，谢谢
