### ISSUE TITLE
能播放H265的视频吗

### ISSUE THREAD

**Issue by GodSadness** [yellowei/CYFFmpeg#2]
可以添加H265支持吗

**Comment by yellowei** [comment]
应该是支持HEVC的，具体可以看下CYPlayer对CYFFmpeg的使用，刚好我在线，验证了hevc是可以播放的。

**Comment by GodSadness** [comment]
> 应该是支持HEVC的，具体可以看下CYPlayer对CYFFmpeg的使用，刚好我在线，验证了hevc是可以播放的。

我看了CYFFmpeg里面只有H264的，没有H265的文件

![image](https://user-images.githubusercontent.com/69337488/170821843-0abeb06a-7dda-42d7-bc4a-c61d4869630a.png)

**Comment by yellowei** [comment]
这个是用来编码的，你是需要编码h265吗？

**Comment by GodSadness** [comment]
> 

播放h265的视频

**Comment by yellowei** [comment]
那本身是支持的，通过cocoapods安装CYFFmpeg直接使用即可，如果需要播放器，也可以直接安装[CYPlayer](https://github.com/yellowei/CYPlayer)

**Comment by GodSadness** [comment]
> 那本身是支持的，通过cocoapods安装CYFFmpeg直接使用即可，如果需要播放器，也可以直接安装[CYPlayer](https://github.com/yellowei/CYPlayer)

好的，谢谢

**Comment by yellowei** [comment]
不用客气，希望这份代码能帮助到你。
